#!/usr/bin/env php
<?php
require_once(__DIR__.'/../vendor/autoload.php');
switch($argv[1])
{
    case 'importvehicles':
        $cli = new VF_CLI_ImportVehicles();
        $cli->main();
        break;
    case 'schema':
        $cli = new VF_CLI_Schema();
        $cli->main();
        break;
}
