#!/usr/bin/env php
<?php
require_once(__DIR__.'/../vendor/autoload.php');

$command = isset($argv[1]) ? $argv[1] : null;
switch($command)
{
    case 'importvehicles':
        $cli = new VF_CLI_ImportVehicles();
        $cli->main();
        break;
    case 'schema':
        $cli = new VF_CLI_Schema();
        $cli->main();
        break;
    default:
        $cli = new VF_CLI();
        $cli->usage();
        break;
}
